/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mauriceliddy;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

class DataInputTest {
    DataInput dataInput = new DataInput();
    String filePath = "C:/VSCode Programs/Week1/Project-0/dataObject.csv";
    List<Athlete> masterList = dataInput.readDataByObject(filePath);

    @Test
    void basicTest() {
        // System.out.println("Working Directory = " + System.getProperty("user.dir"));
        assertEquals("expected", "expected");
    }

    @Test
    void testMastlistIsPopulated() {
        assertNotNull(masterList);
    }

    @Test
    void testAthleteNumber() {
        assertEquals(4, masterList.size());
    }


}
